# Generated by Django 4.0.3 on 2022-03-31 10:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foodplan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название аллергии')),
            ],
            options={
                'verbose_name': 'Аллергия',
                'verbose_name_plural': 'Аллергии',
            },
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название промокода')),
                ('code', models.CharField(max_length=256, unique=True, verbose_name='Промокод')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='С какой даты применим')),
                ('valid_to', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='По какую дату действует')),
                ('discount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Размер скидки в процентах')),
                ('active', models.BooleanField(verbose_name='Активность промокода')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
            },
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.AddField(
            model_name='client',
            name='client_phonenumber',
            field=models.CharField(default='0', max_length=20, verbose_name='Номер клиента'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Когда создана подписка'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='foodplan.menu'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='period',
            field=models.IntegerField(default=1, verbose_name='Период подписки'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='portions',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество порций'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='allergies',
            field=models.ManyToManyField(to='foodplan.allergy'),
        ),
    ]
