# Generated by Django 4.0.3 on 2022-03-31 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodplan', '0002_allergy_promo_alter_subscription_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='subscriptions',
            field=models.ManyToManyField(to='foodplan.subscription'),
        ),
        migrations.AlterField(
            model_name='allergy',
            name='name',
            field=models.CharField(default='Нет', max_length=256, verbose_name='Название аллергии'),
        ),
    ]
