# Generated by Django 4.0.3 on 2022-04-01 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodplan', '0007_dish'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='advice',
            field=models.TextField(default='', verbose_name='Советы'),
        ),
        migrations.AddField(
            model_name='dish',
            name='kkal',
            field=models.IntegerField(default='0', verbose_name='Калорийность'),
        ),
    ]
