# Generated by Django 4.0.3 on 2022-04-01 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodplan', '0008_dish_advice_dish_kkal'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='img',
            field=models.TextField(default='https://static6.depositphotos.com/1006753/572/i/600/depositphotos_5728788-stock-photo-frying-pan.jpg', verbose_name='ссылка на картинку'),
        ),
    ]
