# Generated by Django 4.0.3 on 2022-04-01 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodplan', '0009_dish_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='subscriptions',
        ),
        migrations.AddField(
            model_name='subscription',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='foodplan.client', verbose_name='Хозяин подписки'),
            preserve_default=False,
        ),
    ]
