# Generated by Django 4.0.3 on 2022-04-04 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodplan', '0010_remove_client_subscriptions_subscription_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='ingredientsinfo',
            name='ingredient_amount',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ingredienttype',
            name='name',
            field=models.CharField(default='Без категории', max_length=255),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='DishViewSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodplan.ingredient', verbose_name='ID уже показанного блюда')),
                ('id_sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodplan.recipe', verbose_name='ID подписки')),
            ],
        ),
    ]
