# Generated by Django 4.0.3 on 2022-04-04 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodplan', '0011_alter_category_name_alter_ingredient_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dishviewsubscription',
            name='id_dish',
        ),
        migrations.RemoveField(
            model_name='dishviewsubscription',
            name='id_sub',
        ),
        migrations.AddField(
            model_name='dishviewsubscription',
            name='dish',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='foodplan.dish', verbose_name='ID уже показанного блюда'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dishviewsubscription',
            name='subscription',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='foodplan.subscription', verbose_name='ID подписки'),
            preserve_default=False,
        ),
    ]
