from enum import Enum


class States(Enum):
    ADD_USER_PHONE = 1
    INPUT_NEW_PHONE = 2
    INPUT_USER_NAME = 3
    INPUT_USER_SURNAME = 4
    PERSONAL_AREA = 5
    CURRENT_SUBSCRIPTIONS = 6
    CHOOSE_MENU_TYPE = 7
    CHOOSE_PERSON_AMOUNT = 8
    CHOOSE_MEALS_AMOUNT = 9
    CHOOSE_ALLERGIES = 10
    CHOOSE_SUBSCRIPTIONS_TERM = 11
    OUTPUT_COST_AND_PARAMS = 12
    PAY = 13
    PAY_BANK = 14
    ADD_SUBSCRIPTION_TO_DB = 15
